### ISSUE TITLE
API - Create, delete and update methods

### ISSUE THREAD

**Issue by cfrancocapo** [SpeedCurve-Metrics/SpeedCurve#127]
Hi,
The current API is only supporting GET methods to query data.

When are you going to provide a full experience API usage? We are looking for POST PUT DELETE methods to be able to maintain our tests automatically.

I see that the last release of the API v1 according to your [changelog](https://api.speedcurve.com/#change-log) is from May 2016. Are you still working to improve the API features?

Thanks!

**Comment by zeman** [comment]
Currently we have a manual [bulk import JSON process](http://support.speedcurve.com/knowledgebase/articles/917832-bulk-site-settings-import) for managing settings. We're planning on adding an endpoint to the API over the next couple of weeks to push changes via a JSON upload rather than adding individual methods for create/deleting the various settings.

**Comment by zeman** [comment]
We've just pushed a new [/import endpoint](https://api.speedcurve.com/#import-settings) to the API which you can use to update the settings via a JSON config.

**Comment by cfrancocapo** [comment]
Hi @zeman , is it possible to get a JSON of current settings? Then we will update and test the import endpoint.

Thanks,

**Comment by zeman** [comment]
Yes, you can export current settings. Note that not all settings are covered by the export so don't use the "replace" mode when importing again.

https://api.speedcurve.com/#export-settings
