### ISSUE TITLE
Linkable dots to detail page from custom (favorites) charts 

### ISSUE THREAD

**Issue by tclaeys** [SpeedCurve-Metrics/SpeedCurve#130]
Note sure whether this is change request or bug. But I find myself often clicking at the dots in the custom charts (favorites section), where I would expect to appear a drop down, and the ability to navigate to the detail test page. This would be a handy feature and consistent across all charts.

**Comment by okor** [comment]
I was just about to say the same thing, just started to explore "favorites". I believe they may be lacking this feature because depending on the chart options the stat might be a culmination of more than one test. 

For instance:
<img width="195" alt="screen shot 2016-11-09 at 2 23 21 pm" src="https://cloud.githubusercontent.com/assets/142910/20151428/1b7de97a-a688-11e6-9ca7-22f077605a6f.png">

^ the output (if I understand correctly) is a combination of both the Article and Home tests. I think the solution here would be to link to all of them. Could be a single link to a secondary page with a list of tests or keep the list in the pop up bubble - the bubble option might not be scalable however, depending on your configuration.

**Comment by zeman** [comment]
Correct, the query is an average at the moment so there's no one test to link through to. We'll look at adding a test result that is closest to the average or listing a bunch of them.

We have this on our todo list.

**Comment by zeman** [comment]
We've now added an option for using a "median" stat when building Favorite charts. If you do use median then you're able to click through to the median test result.
