### ISSUE TITLE
Give each chart a linkable URL / #

### ISSUE THREAD

**Issue by jonnywyatt** [SpeedCurve-Metrics/SpeedCurve#133]
For ease of sharing individual charts in the Site / Favorites panes, add an id / # for each so it can be linked to directly?

**Comment by josephwynn-sc** [comment]
Since we implemented [multiple favorites dashboards](https://speedcurve.com/blog/multiple-favorites-dashboards/), all charts in a favorites dashboard have an ID. For now, you can get the ID by inspecting the chart wrapper in your browser developer tools. It will be `chart_NNN_wrapper` where `NNN` is a number:

![chart-id](https://user-images.githubusercontent.com/31634862/32358798-cec8ba6a-c0ad-11e7-9072-d0358b3423ad.png)

Then you can append `#chart_NNN_wrapper` to the URL to link directly to that chart. In the future we could do something like add a permalink icon 🔗 to the chart.
