### ISSUE TITLE
Speed Index not showing if only one Site is selected among many

### ISSUE THREAD

**Issue by abhagupta** [SpeedCurve-Metrics/SpeedCurve#14]
If I have more than one site in an account, and I want to see Speed Index in Benchmark for one particular site and for one template, I am not able to see just Speed Index. The data is shown for median for Page Load, Start Render, Full Load, and Backend, but not for Speed Index, even if I select SpeedIndex from top nav.  Please let me know if I am missing something. I can see SpeedIndex when `All Sites` is selected.

**Comment by zeman** [comment]
This is a bug where the chart should switch to speedindex when it's selected as the metric in this view.

**Comment by zeman** [comment]
This bug only only happens when you select a single site so as a work around you can add leave "All Sites" selected and then see the SpeedIndex and PageSpeed metrics for specific templates.

If you only have one site in your "Settings" you'll need to add a competitor or staging site or even an empty site with no URLs added.

**Comment by ronaldlokers** [comment]
This bug also exists in the responsive tab, the workaround doesn't work over there because you can only select the main site over there.

**Comment by zeman** [comment]
Fixed.
