### ISSUE TITLE
Notes created via the API not showing up on a chart in the UI?

### ISSUE THREAD

**Issue by timmfin** [SpeedCurve-Metrics/SpeedCurve#142]
I've been trying to create a note via a request like this:

```
curl "https://api.speedcurve.com/v1/notes" \
  -u XXX:YYY \
  --request POST \
  --data timestamp=148147880 \
  --data site_id=22335 \
  --data note=Testing%20deploy%20note%20via%20API2

{"note_id":85613,"site_id":22335,"timestamp":"148147880","note":"Testing deploy note via API2","detail":""}
```
But I am not seeing that show up on the chart (however I am seeing a note that I manually created via the UI by clicking on the chart line). This screenshot tries to illustrate the site in question, the list of all notes associated with it, and the detail of one note created via the API:

![image](https://cloud.githubusercontent.com/assets/60455/21189729/a2476f28-c1ed-11e6-8c23-dea172274e7a.png)

**Comment by zeman** [comment]
Hi Tim,

Even though the note has been added it won't show until after we have some data to show for the same timespan on the chart. You can see the note now since there's a round of tests that completed just after you added the note.

If you're adding a note and deploying at the same time it will take around 5min for the first set of tests to populate the chart and the note will show.

If you're using the deploy API you can add a note at the same time, rather than calling two different endpoints.

**Comment by timmfin** [comment]
Ok, good to know.

FYI, I for one of my test notes I tried to create it with a timestamp of a few days ago... however my timestamp had a typo (missing a single 0) which caused it to be 40+ years ago and not just a few days ago. My bad! 😿
