### ISSUE TITLE
Budget alert does not indicate Site and/or URL in Webhook notification

### ISSUE THREAD

**Issue by jleatherman** [SpeedCurve-Metrics/SpeedCurve#158]
If I have a budget alert configured for all sites/urls, I would expect that when an alert fires a webhook notification, the payload would have the specific site/url that caused the violation.

Currently, this only shows the Organization (or Team) name.

![image](https://user-images.githubusercontent.com/12204030/27191368-6e3ea4ea-51ac-11e7-84e3-cea38d2ef916.png)

**Comment by jleatherman** [comment]
I did some reconfiguration and made my Sites 1:1 with my Teams, which made this no longer an issue. However, I feel that this behavior is still incorrect, and the notification should include the name of the specific URL being monitored.

**Comment by josephwynn-sc** [comment]
We've just pushed some changes so that the webhook alerts have the same amount of detail as email alerts. This includes URL label, site name, browser, and region.

![screenshot from 2017-11-24 16-54-37](https://user-images.githubusercontent.com/31634862/33292054-be392d64-d42c-11e7-8451-aab02f319c85.png)
