### ISSUE TITLE
Favorites chart editor doesn't work in Firefox

### ISSUE THREAD

**Issue by stevesouders** [SpeedCurve-Metrics/SpeedCurve#171]
- Go to Favorites panel *in Firefox*
- Edit a panel and save
- Click edit again

Expected: Edit form opens

Actual: Nothing (looks the sortable mechanism gets triggered instead, as sortable classes get added in DOM)

**Comment by josephwynn-sc** [comment]
I was able to replicate this. The issue is that the click event handlers in the charts container stop firing. Steve was onto something with the sortable classes - the sortable event handlers still fire which is suspicious. Rather than dig to find the root cause I grabbed the latest version of Sortable.js (1.6.1; we're on 1.4.2) from GitHub. This seemed to fix the issue.

I will do a bunch of browser regression testing to make sure upgrading Sortable.js doesn't break anything. If that comes back clean then @stevesouders / @zeman does that sound like a reasonable fix to you?

**Comment by zeman** [comment]
Yep, if an upgrade fixes the issue that's awesome.

**Comment by josephwynn-sc** [comment]
I've pushed the upgrade to dev. It's looking good in Firefox, Chrome, and Edge. @zeman or @stevesouders maybe you could have a quick sanity check in Safari to make sure re-ordering Favorites charts works?

**Comment by zeman** [comment]
Checked Safari, works great.
