### ISSUE TITLE
Cross-team view-only access

### ISSUE THREAD

**Issue by parshap** [SpeedCurve-Metrics/SpeedCurve#179]
Org admins are great because you can see data from all teams. This is useful for anyone does does horizontal work across teams or otherwise wants insight to data across teams.

Right now I'm just adding those people as org admins, but I am getting increasingly nervous that one of them will accidentally edit another team's settings. Additionally, I think it'd actually be useful for *everyone* to be able to see data across teams, but I can't make *everyone* an org admin.

My proposal:

* Add an org-level option that enables cross-team view-only access for all users.
* Optionally, add a user-level option to grant only that user cross-team view-only access.
* Team admins continue to be per-team and are the only users that can edit that team settings.

Potential issues:

* Users might get lost about what team's page their on and find it difficult to get back to their team. You may consider making the current team more prominent in the UI and giving quick access to teams the user is a team admin of.

**Comment by JeroenVdb** [comment]
I have about of the same request. I'll give some more context about our use-case.

We have an organisation with multiple teams working on their website(s). I would like to use the "teams" feature give all teams separate budgets and let them manage their dashboards and specific settings on their own.

Why we can't use the teams feature for now?
- Because WebsiteA.com is in another team as WebsiteB.com teams we can't compare them in the benchmark or in the custom dashboards, this can be useful because those websites can be seen as competitors. To accomplish this we would have to run tests for WebsiteA.com en competitorA.com on all teams. 
 
How the "teams" are now organised fits an "organisation with multiple private clients" structure.

Of course there are some downsides to merge all these together. Always seeing **all** sites will also be unclear.

- Maybe TeamA should be able to share WebsiteA.be with TeamB,
- and TeamB be able to choose which sites that are shared with them to "use/show" in their dashboards

**Comment by josebolos** [comment]
Here at Springer Nature we have the same problem as @JeroenVdb.

Our use case is: we currently have 12+ teams working on different applications delivering content on 5 different public-facing domain names.

Currently, each one of those teams is currently set up as a different team on SpeedCurve, as they may have different needs regarding what to test and when, how and when to be alerted, if/when to trigger tests after a successful deployment, etc.

Setting them up as a single team as mentioned above is not possible for us because it would be impossible to manage so many URLs, settings, and specially budget alerts as a single SpeedCurve team.

Unfortunately, that means that if, for example, two teams want to run a comparison with a specific competitor, or compare themselves against pages managed by other teams, all of these URLs need to be tested again for each team wanting to be compared against.

It would be better for us (organisationally speaking) if for example sites could be defined once across the whole organisation, and then teams would be defined as a set of permissions to view/modify each site, and maybe also some specific alert settings. I imagine that would be a massive change so I understand if this is not what you have in mind!

**Comment by josephwynn-sc** [comment]
We're reviewing our public issues as a team and have decided to close this ticket. We realise that having hard boundaries between teams can make it difficult to compare data, but we have no plans to introduce a cross-team view within the SpeedCurve UI. You can build your own cross-team views by using the [SpeedCurve API](https://api.speedcurve.com/#speedcurve-v1-api).
