### ISSUE TITLE
Content sizes after upgrading to faster test agents seemingly incorrect

### ISSUE THREAD

**Issue by franjohn21** [SpeedCurve-Metrics/SpeedCurve#184]
I just tried upgrading one of our teams' agents to the C4.large instance and seeing a large spike in content sizes. This also correlates to a seemingly different behavior in HTTP2 stream prioritization. 

![screen shot 2018-02-06 at 11 57 01 am](https://user-images.githubusercontent.com/7452924/35881187-e3ffa318-0b34-11e8-9bbd-e68071af157c.png)

This is the same asset before and after the change (both requests are cache hits by our CDN):
![screen shot 2018-02-06 at 11 51 58 am](https://user-images.githubusercontent.com/7452924/35881137-b4c3a11c-0b34-11e8-97ae-2a7894185d7c.png)

Could this be Chrome operating differently due to the improved performance characteristics? Looking at the user agent it looks like we also upgraded from Chrome 62 to Chrome 64 so maybe that has some impact? For what it's worth, the timeline trace in chrome reports the correct encoded size for this asset.

**Comment by zeman** [comment]
Hi Francis,

We're looking into this but I suspect the prioritization change is due to Chrome 64 and the change in bytes in is due to switching from Windows to Linux.

**Comment by pmeenan** [comment]
If you can send me the page in question (email if it shouldn't be public) I can look at the byte sizes.  It's possible that the new agent ins including more of the stream overhead, headers or something else that wasn't captured before.  The uncompressed sizes look the same so it must be something in the raw byte stream size extraction.

As far as the prioritization goes, There was an experiment rolling (I think in 62) that delayed HTTP/2 requests like it did for HTTP/1 (don't load non-critical resources until after the critical resources have loaded) that I think was disabled in 63 because it made some of the metrics worse.  

That said, it changed from "LOW" to "LOWEST" which I wouldn't have expected to happen, just the stream dependency so something else more subtle may be going on.  If that's the first script in a list of end-of-body scripts and the main parser got to it before it started to load  then I could see why in 62 with the experiment enabled it would be loaded at a higher priority (if the parser blocks on a script before it starts to load the priority will be raised).  In 64 with the experiment disabled the script is fetched as soon as the preload scanner discovers it but it gets a LOWEST priority because it is a late script and the parser hasn't reached it yet.

**Comment by franjohn21** [comment]
[Page in question](https://www.nerdwallet.com) | [wpt before](https://wpt1.speedcurve.com/result/180205_G8_920919fc3313f34a2361568c65c02f06/) | [wpt after](https://wpt1.speedcurve.com/result/180206_M6_7f2743f414952bf2930097af17fdb331/) 

Thanks for the clarification @pmeenan. The script is indeed defined in later the `body`.

**Comment by asuth** [comment]
We're seeing the same issue. We're also seeing instability in content sizes between tests, which we don't expect.

**Comment by Friss** [comment]
We are seeing the same thing at HubSpot for our tests where the reported weight of the page jumped 500KB across CSS and JS assets.

**Comment by pmeenan** [comment]
Should be [fixed now](https://github.com/WPO-Foundation/wptagent/commit/9670a239bb01bf4c1b7b05217cb350e4397ae76f).

[Sample test](https://www.webpagetest.org/result/180214_01_1ee0c8f98edb7e3ee2a14cc23a79fa38/1/details/#step1_request13):

![image](https://user-images.githubusercontent.com/444165/36221510-485ebfee-118c-11e8-98e1-f9cd6a10f150.png)

The public WebPageTest agents will pick up the fix over the next hour (not sure if @zeman is using auto-updating AMI's or not).  FWIW, there are also new AMI's that disable IPv6 because it causes Firefox to have a slower DNS lookup.

As far as the fix goes, Chrome's timestamping of some of the events can be out of order (apparently) so the "loadingFinished" event which comes later in a trace actually has a timestamp earlier than the dataReceived events (which actually happened earlier).

WebPageTest will use the object size if it is available in the loadingFinished event (usually is) but as a fallback it will add up the dataReceived bytes.  Since they were timestampped backwards it was starting with the total size and adding the incremental bytes as those events came in (effectively double-counting).

The fix explicitly identifies when it has processed the size from the loadingFinished event and does not increment the size if the finished event had already been processed.

**Comment by tammyeverts** [comment]
Awesome! We're having a Pat Meenan lovefest over on SpeedCurve Slack. Are your ears burning, Pat? ;)

**Comment by pmeenan** [comment]
They weren't but I'm blushing now :-)

Let me know if you see any other oddities.  I'm really looking forward to sunsetting the old agents (particularly since they will stop working for Chrome in a couple of months).

This fix will also percolate through to the HTTP Archive testing which has been running on the Linux agents for at least six months so it will be interesting to see how much the overall stats drop.

**Comment by zeman** [comment]
Woot, thanks @pmeenan, you sir are a legend!

**Comment by olpeh** [comment]
Thank you for fixing it this quickly! 👍

**Comment by kaelig** [comment]
Thanks @pmeenan! Our graphs look back to normal :)
