### ISSUE TITLE
Email report is not formatted well

### ISSUE THREAD

**Issue by jleatherman** [SpeedCurve-Metrics/SpeedCurve#197]
### Issue type

  - [ ] Feature request
  - [X] Bug report
  - [ ] Question (please email questions to support@speedcurve.com)

### Current behaviour

The reports that are emailed weekly are not formatted in a way that it can be viewed without scrolling horizontally (Outlook 2016, in this case). Due to this, I am not yet sharing reports with the dev teams.

Preview:
![image](https://user-images.githubusercontent.com/12204030/44352600-add0ff80-a459-11e8-9630-cadcd4df8759.png)

Opened:
![image](https://user-images.githubusercontent.com/12204030/44352706-ecff5080-a459-11e8-8612-89d94b3d7fdf.png)

### Expected behaviour

The report should be formatted to fit into the preview window, and should expand to the full width when opening the message.

Example preview:

![image](https://user-images.githubusercontent.com/12204030/44352874-4ff0e780-a45a-11e8-8dcc-7190f9ec8727.png)

Example opened:

![image](https://user-images.githubusercontent.com/12204030/44352913-626b2100-a45a-11e8-9c7f-76f76dcae486.png)

**Comment by josephwynn-sc** [comment]
Thanks for reporting this, @jleatherman! We've updated the email template so that the focus charts at the top are a fixed width of 800px on email clients that don't support (much) CSS like Outlook. Unfortunately we can't format this email properly in both the preview window _and_ the expanded view, since the focus chart images are meant to be `width: 100%` and Outlook only supports fixed-width images. We could reduce the fixed width even further to something like 600px if the consensus is that 800 is too wide.
