### ISSUE TITLE
"PTST" isn't always in the user agent string

### ISSUE THREAD

**Issue by stevenmichaelthomas** [SpeedCurve-Metrics/SpeedCurve#30]
"PTST" isn't always in the user agent string, though presumably it should be: http://support.speedcurve.com/knowledgebase/articles/354878-how-do-the-browser-testing-agents-work

For example, from this test: https://wpt.speedcurve.com/details.php?test=151004_5W_a2e4e5b30c9f993971e77ea2b43f5320&run=2&cached=0

<img width="400" alt="screen shot 2015-10-05 at 2 57 18 pm" src="https://cloud.githubusercontent.com/assets/997133/10290320/789631a6-6b71-11e5-81d2-84dd5b2836e3.png">

/cc @brysongilbert who reported the issue in one of our repos :smile:

**Comment by brysongilbert** [comment]
Extra background info on this: when we are running an A/B test on a page that is also monitored in SpeedCurve, SpeedCurve becomes useless (for that page) because the WPT bots aren't always served the same variant of the A/B. Our solution is to force the "original" variant of a test when we detect the SpeedCurve agent via the UA string, but of course we can't do this reliably unless some part of the string is predictable.

**Comment by zeman** [comment]
There appears to be a bug in WebPageTest (WPT) where the correct UA is not always set for https requests. We're following this one up with Pat from WPT.

https://github.com/WPO-Foundation/webpagetest/issues/488

If on an Enterprise plan you can use the WPT scripting capability to add an extra header or cookie to your tests and use that to force the correct A/B test rather than rely on the UA string.

**Comment by zeman** [comment]
Our WPT agents have been updated to the latest agent released today which adds the "PTST" string back in for https requests in Chrome, Firefox & IE. Sounds like support for Safari will be unlikely.

**Comment by zeman** [comment]
Moving to low priority as only Safari is missing.

**Comment by brysongilbert** [comment]
:raised_hands: Awesome!
