### ISSUE TITLE
Api Key ? account page ?

### ISSUE THREAD

**Issue by joaogbcravo** [SpeedCurve-Metrics/SpeedCurve#31]
Not sure this is really a bug, but on your documentation: 
https://api.speedcurve.com/#authentication
it says that we can find our API key in  https://speedcurve.com/account/
However this give me a 404. 

Where can I find my api key?

cheers,
João

**Comment by zeman** [comment]
Docs updated. You can now find the API key on the **Admin > Teams** page.

**Comment by philberryman** [comment]
Has it moved again? I can't see it on that page.

**Comment by gsdevme** [comment]
Yeah I can't seem to find how to generate an API key either.

**Comment by josephwynn-sc** [comment]
It's a little confusing, but API keys live in the **Admin > Teams** page, rather than just the **Team** page. If you don't have full admin privileges you will not be able to see the Admin navigation item:

![Screenshot from 2020-06-19 11-08-41](https://user-images.githubusercontent.com/31634862/85080462-5c445800-b21d-11ea-816d-ffd86c9745f3.png)

With full admin privileges you will see this:

![Screenshot from 2020-06-19 11-08-41](https://user-images.githubusercontent.com/31634862/85080516-7d0cad80-b21d-11ea-926c-fb034808a6e5.png)
