### ISSUE TITLE
Non ASCII characters within URL or Profile name

### ISSUE THREAD

**Issue by machal** [SpeedCurve-Metrics/SpeedCurve#34]
You can see it within URL or in my name: 

![image](https://cloud.githubusercontent.com/assets/16641/10525030/d9ee67d4-7382-11e5-8060-6ed6444d146d.png)

When I log in, I do not see any data, even though I have paid account. This is something new.

**Comment by zeman** [comment]
I've updated the url snippet for you so your account is functional again and we'll look into the non ASCII character issue.

**Comment by machal** [comment]
It works perfectly. Thank you!

**Comment by zeman** [comment]
Jonathan, can you do a check for when adding the URL stubs and make sure they're valid. If not clean them up so they can be saved and don't break the URL. User can then edit later in "Team Info" page.

**Comment by jonathanhardie** [comment]
I can't really think of a good comprehensive fix for this – for languages using latin characters we could do some set transformations:  õ --> o etc, but that strategy falls down as soon as people start using non-latin encode characters.  Since this is initially generated from the org/team name, would the best thing to do is just enforce the org/team names to be in ascii?  Not a great solution.  Otherwise, maybe we should just allow unicode everywhere.  It's pretty simple to just store the names as unicode in the db, and spit them out as url encoded unicode.  The only thing that would need to be changed then would be the regexes in the url rewriting, to handle this character range I think?

**Comment by zeman** [comment]
Let's drop any non ascii characters for the url snippet. The org name is fine.

**Comment by zeman** [comment]
Fixed.
