### ISSUE TITLE
Editing the script of an existing template throws error

### ISSUE THREAD

**Issue by swastikdash** [SpeedCurve-Metrics/SpeedCurve#37]
When i try to edit the existing script of a template and save it, it throws an error "There was an error saving scripts. Please contact support."

Also if i add a new template and add a script, the new template automatically takes the script of the previous template.

![speedcurveerror](https://cloud.githubusercontent.com/assets/15227056/10630332/8aa156da-77f3-11e5-8037-ee9b333227c4.jpg)

**Comment by zeman** [comment]
The error means that more than one person is monitoring the same URL and the script is now in conflict across the accounts so we don't save any edits to it.

The best way to resolve it is to change the template URL to something unique eg. "http://yourwebsite.com/withscript/". This will create a unique URL in the system but since the actual URL that gets tested is controlled by the "navigate" command in the script it will still test the URL you specify but the template URL we use to look up tests will now be unique to your account.

Note that if you do change the template URL you will no longer see your existing history as we use the URL as a key to look up the tests.

We're currently working on redesigning the way the settings work and this conflict situation will go away once we roll that update out.
