### ISSUE TITLE
[Webhook] Integration for HipChat

### ISSUE THREAD

**Issue by irkanu** [SpeedCurve-Metrics/SpeedCurve#53]
I'd like to request the webhook for Speedcurve notifications be able to POST to HipChat's API. For example, if I have a HipChat webhook configured:

> https://{{subdomain}}.hipchat.com/v2/room/{{id}}/notification?auth_token={{auth_token}}

The webhook for Speedcurve should detect HipChat and send the appropriate data for a room notification. Further reading below:

> https://www.hipchat.com/docs/apiv2/method/send_room_notification

**Comment by zeman** [comment]
Jonathan, can you take a look at detecting HipChat in the webhook URL and changing the format of what we push to HipChat.

**Comment by jonathanhardie** [comment]
I've added initial basic support for this (the formatting could perhaps be prettier, but I had no success getting HipChats' "cards" to work).  One thing to note is that hipchat allows users to run their own hip chat server on their own domain.  I'm not sure that we can support that case, since it's pretty hard to detect if there's no 'hipchat.com' present in the webhook url.
