### ISSUE TITLE
PTST/282

### ISSUE THREAD

**Issue by laurentgoudet** [SpeedCurve-Metrics/SpeedCurve#90]
Has anything changed with SpeedCurve on June 6th between 4PM and 10PM (US East)? All our graphs have jumped...

<img width="1224" alt="screen shot 2016-06-14 at 1 52 49 pm" src="https://cloud.githubusercontent.com/assets/2169585/16041733/6447224a-3237-11e6-9ace-6e169798e12d.png">

...and it seems due to the TCP timings going crazy, no matter the host (Akamai, FB, Cloudfront...)

<img width="536" alt="screen shot 2016-06-14 at 1 49 34 pm" src="https://cloud.githubusercontent.com/assets/2169585/16041772/985c736e-3237-11e6-8521-d01ade36b841.png">

<img width="624" alt="screen shot 2016-06-14 at 1 47 50 pm" src="https://cloud.githubusercontent.com/assets/2169585/16041797/b9740a6c-3237-11e6-9c52-87c49685f669.png">

The only thing that seems to have changed (no relevant code change on our side) is the test instances UA, which seems to consistently show PTST/281 before & PTST/282 after the jump, which possibly reflect a update of the platform? Thanks!

**Comment by zeman** [comment]
We're investigating this and have also upgraded to the latest WebPageTest agent 283 to see if it also shows the same behaviour.

**Comment by pmeenan** [comment]
My guess would be [this change](https://github.com/WPO-Foundation/webpagetest/commit/dda9d248410e1b8e9cce627700e36d2b060c06a9) which fixed the ipfw queue configuration but every test I have seen actually showed the opposite reaction with things [getting faster](http://www.webpagetest.org/benchmarks/view.php?benchmark=browsers&aggregate=avg&days=31) and more stable.  There were only a few other changes between 281 and 282 but that one jumps out as the most likely.

If you can share the full test URL (after /contest...) I can see if I can reproduce the issue and track it down.  Maybe something with running on EC2 isn't happy with the change.

**Comment by laurentgoudet** [comment]
The full url of that particular test was https://www.freelancer.com/contest/design-a-logo-for-studentsurvival-guide-196572.html (e.g. https://wpt.speedcurve.com/result/160607_H9_4fce0fd3ec5b071266d3c4173dce2542/), with most pages having similar issues (e.g., https://wpt.speedcurve.com/result/160609_JR_ca37051bded9750ebdde992296939361/)

**Comment by pmeenan** [comment]
So far it looks like the site is completely CPU constrained (between JS and layout) and the changes in 282 are causing the test machines to use slightly more CPU which is enough to push things over the edge.  Taking a look to see if tweaks to the dummynet shaping can be made that would reduce the CPU utilization to where it was before but odds are that if it is because of the dummynet change it won't be going back (because of the general improvement in consistency across most testing).

**Comment by jangie** [comment]
@pmeenan just for clarification, what is meant by "causing the test machines to use slightly more CPU which is enough to push things over the edge"? Is there some CPU-time threshold at which measurements become inconsistent between PTST/281 and PTST/282? If so, what is that threshold, and is there any indication of what causes this?

**Comment by pmeenan** [comment]
Well, the limit is really the threshold at which point a page becomes CPU-constrained vs network-constrained (under specific network conditions anyway).  I'm seeing more and more sites where the main thread on the browser is blocked for close to 100% of the load time, mostly doing JS parse/compile/execution.  In those cases, any additional machine overhead will cause the times to take longer.

**Comment by ynori7** [comment]
![june6speedcurve](https://cloud.githubusercontent.com/assets/3975795/16187887/269cc396-36d3-11e6-990d-95a0704d9e9a.png)

I'm also experiencing the same issues. The attached screenshow shows the speedindex for a page (a "clean" version with the ad and tracking domains blocked, so they shouldn't affect anything). Starting from the 6th or 7th of June the load times and start render times jumped way up (from 1.1s start render to 2.5s). No one has touched anything in the code for this project, so nothing should have changed since around the 20th of May.

**Comment by okor** [comment]
@zeman It would be really helpful to indicate in the timeline that a change to the backend was made, for each WPT upgrade. Like using a deploy annotation. This way users can at least be aware of the possibility that something changed outside of their control and might not have anything to do with the site content. If you could do this retroactively that would be very helpful.

**Comment by zeman** [comment]
@okor the agents are frequently updated, often weekly and sometimes daily when issues are being  resolved. We don't want to spam users charts will all those notes.

**Comment by okor** [comment]
@zeman Ok, perhaps a log then? I would prefer "spam" to lack of information, personally. But we deploy a lot each day so our chart is pretty spammed up as it. But when the thing you are using to test stuff changes ... the results can/will be less predictable. Without any visibility into those details I'm flying blind. 

We spent hours trying to track down a problem that didn't exist. That's my motivation for some sort of log. Pretty sure there are other in the same boat.

**Comment by okor** [comment]
Thanks Mark, that will be very helpful : )

**Comment by zeman** [comment]
This change in metrics has been caused by an update to the WebPageTest agents. The network throttling code has been improved but it has led to an increase in the CPU used by the agent therefore leaving less CPU for the actual tests to run. We've seen URLs with lots of JS and high CPU usage slow down slightly as captured in your graphs. Not all URLs are affected, only those with already high CPU usage.

In response we're accelerate plans we already had to introduce extra choices for agents with different performance profiles. This doesn't solve the problem but it will give you choices about what agents to run. We'll be recommending people run both the current agent to mimic low CPU devices like mobile, and a higher CPU agent to mimic desktops.

Sorry if this has caused you any issues, it's the first time we've seen a WebPageTest agent update affect metrics like this and was unexpected.

We've added a simple product updates section where we'll note any updated to the WebPageTest agents so you can check to see if SpeedCurve changes might be affecting your metrics before looking at your own code. We endeavor to keep the environment as stable as possible.  

https://speedcurve.com/updates/
